// import './index.pug'
import $ from 'jquery'
import 'slick-slider/slick/slick.css'
import 'slick-slider/slick/slick'
import 'animate.css/animate.css'
//import scrolloverflow from 'fullpage.js/vendors/scrolloverflow'
//import fullpage from 'fullpage.js'
// import 'jquery-form-styler/dist/jquery.formstyler.theme.css'
import './js/common'
import 'normalize.css'
import './sass/main.sass'

// import 'vue'
// import Bootstrap from 'bootstrap/dist/css/bootstrap.min.css'
// import Vue from 'vue'
// window.Vue = require('vue')
